# ================================
# Lister toutes les inscriptions
# ================================
GET http://localhost:3000/inscriptions
Accept: application/json

###

# =====================================
# Récupérer une inscription par matricule
# Remplace 12345 par le matricule réel
# =====================================
GET http://localhost:3000/inscriptions/2023001
Accept: application/json